/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2023-03-21 14:26:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Pelicula.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Pelicula");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("Plantilla utilizada para prÃ¡cticas de ProgramaciÃ³n, Centro Nelson.\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<title>Práctica Programación</title>\r\n");
      out.write("		<meta charset=\"ISO-8859-1\">\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("		<meta name=\"description\" content=\"\" />\r\n");
      out.write("		<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("	</head>\r\n");
      out.write("	<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Header -->\r\n");
      out.write("			<header id=\"header\">\r\n");
      out.write("				<a class=\"logo\" href=\"index.html\">Centro Nelson</a>\r\n");
      out.write("				<nav>\r\n");
      out.write("					<a href=\"#menu\">Menú</a>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</header>\r\n");
      out.write("\r\n");
      out.write("		<!-- Nav -->\r\n");
      out.write("			<nav id=\"menu\">\r\n");
      out.write("				<ul class=\"links\">\r\n");
      out.write("					<li><a href=\"index.html\">Inicio</a></li>\r\n");
      out.write("					<li><a href=\"\">Enlace 1</a></li>\r\n");
      out.write("					<li><a href=\"\">Enlace 2</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("		<!-- Heading -->\r\n");
      out.write("			<div id=\"heading\" >\r\n");
      out.write("				<h1>Práctica Peliculas</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Main -->\r\n");
      out.write("			<section id=\"main\" class=\"wrapper\">\r\n");
      out.write("				<div class=\"inner\">\r\n");
      out.write("					<div class=\"content\">\r\n");
      out.write("						<header>\r\n");
      out.write("							<h2>Listado de Peliculas del archivo peliculas.txt</h2>\r\n");
      out.write("						</header>\r\n");
      out.write("						<!--  -->\r\n");
      out.write("						");
ArrayList<Pelicula> datosPelis = Main.devolverArrayPeliculas(); 
      out.write("\r\n");
      out.write("						");

						for (int i = 0; i < datosPelis.size(); i++) {
							out.print("<div class='pelicula'>");
							
							out.print("<h3><b>" + datosPelis.get(i).getTitulo() + "</b></h3>");
							out.print("<img src = 'images/caratulas/" + datosPelis.get(i).getCodigo() + ".jpg' style='float: right; position: relative; width: 20%;'>");
							out.print("<p><b>Año: " + datosPelis.get(i).getYear() + "</b></p>");
							out.print("<p><b>Duración: " + datosPelis.get(i).getDuracion() + " min</b></p>");
							
							// Pendiente
							out.print("<p><b>País:</b><span> <img src = 'images/banderas/" + datosPelis.get(i).getPais().replace(" ", "").toLowerCase() + ".png' style=\"width: 18px; height: 12px\"> </span></p>");
							out.print("<p><b>Dirección: " + datosPelis.get(i).getDireccion() + "</b></p>");
							out.print("<p><b>Guión: " + datosPelis.get(i).getGuion() + "</b></p>");
							out.print("<p><b>Fotografia: " + datosPelis.get(i).getFotografia() + "</b></p>");
							out.print("<p><b>Reparto: " + datosPelis.get(i).getReparto() + "</b></p>");
							
							out.print("</div>");
							out.print("<hr>");
						}
							
						
      out.write("\r\n");
      out.write("						<!--  -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("			<footer id=\"footer\">\r\n");
      out.write("				<div class=\"inner\">\r\n");
      out.write("					<div class=\"content\">\r\n");
      out.write("						<section>\r\n");
      out.write("							<h3>Accumsan montes viverra</h3>\r\n");
      out.write("							<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing. Lorem ipsum dolor vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing sed feugiat eu faucibus. Integer ac sed amet praesent. Nunc lacinia ante nunc ac gravida.</p>\r\n");
      out.write("						</section>\r\n");
      out.write("						<section>\r\n");
      out.write("							<h4>Sem turpis amet semper</h4>\r\n");
      out.write("							<ul class=\"alt\">\r\n");
      out.write("								<li><a href=\"#\">Dolor pulvinar sed etiam.</a></li>\r\n");
      out.write("								<li><a href=\"#\">Etiam vel lorem sed amet.</a></li>\r\n");
      out.write("								<li><a href=\"#\">Felis enim feugiat viverra.</a></li>\r\n");
      out.write("								<li><a href=\"#\">Dolor pulvinar magna etiam.</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</section>\r\n");
      out.write("						<section>\r\n");
      out.write("							<h4>Magna sed ipsum</h4>\r\n");
      out.write("							<ul class=\"plain\">\r\n");
      out.write("								<li><a href=\"#\"><i class=\"icon fa-twitter\">&nbsp;</i>Twitter</a></li>\r\n");
      out.write("								<li><a href=\"#\"><i class=\"icon fa-facebook\">&nbsp;</i>Facebook</a></li>\r\n");
      out.write("								<li><a href=\"#\"><i class=\"icon fa-instagram\">&nbsp;</i>Instagram</a></li>\r\n");
      out.write("								<li><a href=\"#\"><i class=\"icon fa-github\">&nbsp;</i>Github</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</section>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"copyright\">\r\n");
      out.write("						&copy;  <a href=\"https://www.centronelson.org\">Centro Nelson</a>.\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</footer>\r\n");
      out.write("\r\n");
      out.write("		<!-- Scripts -->\r\n");
      out.write("			<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
