/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2023-05-27 23:14:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import FIFA.*;
import java.util.*;

public final class onceIdeal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("FIFA");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html\">\r\n");
      out.write("	\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("	<!-- 1 -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/mainPersonal.css\" />	\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.css\" />\r\n");
      out.write("	\r\n");
      out.write("	<title>Proyecto Web FIFA23</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"is-preload\">\r\n");
      out.write("		<div id=\"page-wrapper\">\r\n");
      out.write("		\r\n");
      out.write("			<!-- Header -->\r\n");
      out.write("				<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Logo -->\r\n");
      out.write("						<h1><a href=\"index.jsp\" id=\"logo\">FIFA23</a></a></h1>\r\n");
      out.write("\r\n");
      out.write("					<!-- Nav -->\r\n");
      out.write("						<nav id=\"nav\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"current\"><a href=\"index.jsp\">Inicio</a></li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<a href=\"#\">Listados</a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"ligas.jsp\">FIFA 23 Ligas</a></li>\r\n");
      out.write("										<li><a href=\"equipos.jsp\">FIFA 23 Equipos</a></li>\r\n");
      out.write("										<li><a href=\"jugadores.jsp\">FIFA 23 Jugadores</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<a href=\"#\">Operaciones</a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>\r\n");
      out.write("											<a href=\"#\">Jugadores</a>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"operaciones.jsp?tipo=altajugador\">Alta Jugador</a></li>\r\n");
      out.write("												<li><a href=\"#\">Baja Jugador</a></li>\r\n");
      out.write("												<li><a href=\"#\">Modificar Jugador</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</li>\r\n");
      out.write("										<li>\r\n");
      out.write("											<a href=\"#\">Equipos</a>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\">Alta Equipo</a></li>\r\n");
      out.write("												<li><a href=\"#\">Baja Equipo</a></li>\r\n");
      out.write("												<li><a href=\"#\">Modificar Equipo</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</li>\r\n");
      out.write("										<li>\r\n");
      out.write("											<a href=\"#\">Ligas</a>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\">Alta Liga</a></li>\r\n");
      out.write("												<li><a href=\"#\">Baja Liga</a></li>\r\n");
      out.write("												<li><a href=\"#\">Modificar Liga</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</li>\r\n");
      out.write("										<li>\r\n");
      out.write("											<a href=\"#\">Cartas</a>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\">Alta Carta</a></li>\r\n");
      out.write("												<li><a href=\"#\">Baja Carta</a></li>\r\n");
      out.write("												<li><a href=\"#\">Modificar Carta</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li ><a href=\"#\">Simulador</a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"#\">Construye tu Equipo</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Main -->\r\n");
      out.write("				<section class=\"wrapper style1\"\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Content -->\r\n");
      out.write("							\r\n");
      out.write("								<article>\r\n");
      out.write("									\r\n");
      out.write("								<section class=\"col-6 col-12-narrower\">\r\n");
      out.write("								<h3>Elige a tu 11 ideal:</h3>\r\n");
      out.write("								\r\n");
      out.write("								<!-- Formulario -->\r\n");
      out.write("								");

								BDController conexion = new BDController();
								
								ArrayList<Jugador> porteros = conexion.damePorteros();
								ArrayList<Jugador> defCentrales = conexion.dameDefensasCentrales();
								ArrayList<Jugador> latDrc = conexion.dameLateralesDerechos();
								ArrayList<Jugador> latIzq = conexion.dameLateralesIzquierdos();
								ArrayList<Jugador> delanteros = conexion.dameDelanteros();
								ArrayList<Jugador> centrocampistas = conexion.dameCentrocampistas();
								ArrayList<Jugador> extremosIzq = conexion.dameExtremosIzqdos();
								ArrayList<Jugador> extremosDrc = conexion.dameExtremosDrchos();
								
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								<form action=\"onceIdeal2.jsp\" method=\"post\">\r\n");
      out.write("									<div class=\"row gtr-50\">\r\n");
      out.write("									\r\n");
      out.write("										<!-- INICIO -->\r\n");
      out.write("										<div class=\"\">\r\n");
      out.write("										\r\n");
      out.write("											<!-- Portero -->\r\n");
      out.write("											<label>Portero:</label>\r\n");
      out.write("											<select id=\"codPortero\" name=\"codPortero\">\r\n");
      out.write("											");

											for(int i = 0; i < porteros.size(); i++) { 
      out.write("\r\n");
      out.write("												<option data-img_src=\"images/jugadores/");
      out.print(porteros.get(i).getCod_jugador() );
      out.write(".png\" value=\"");
      out.print(porteros.get(i).getCod_jugador());
      out.write('"');
      out.write('>');
      out.print(porteros.get(i).getNombre() );
      out.write("</option>\r\n");
      out.write("											");
}; 
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("										\r\n");
      out.write("											<!-- Delantero 1 -->\r\n");
      out.write("											<label>Delantero 1:</label>\r\n");
      out.write("											<select id=\"codDelantero1\" name=\"codDelantero1\">\r\n");
      out.write("											");

											for(int i = 0; i < delanteros.size(); i++) { 
      out.write("\r\n");
      out.write("												<option data-img_src=\"images/jugadores/");
      out.print(delanteros.get(i).getCod_jugador() );
      out.write(".png\" value=\"");
      out.print(delanteros.get(i).getCod_jugador());
      out.write('"');
      out.write('>');
      out.print(delanteros.get(i).getNombre() );
      out.write("</option>\r\n");
      out.write("											");
}; 
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("											\r\n");
      out.write("										</div>\r\n");
      out.write("										\r\n");
      out.write("										<div class=\"\">\r\n");
      out.write("											<!-- Defensa central 1 -->\r\n");
      out.write("											<label>Defensa central 1:</label>\r\n");
      out.write("											<select id=\"codDefCentral1\" name=\"codDefCentral1\">\r\n");
      out.write("											");

											for(int i = 0; i < defCentrales.size(); i++) { 
      out.write("\r\n");
      out.write("												<option data-img_src=\"images/jugadores/");
      out.print(defCentrales.get(i).getCod_jugador() );
      out.write(".png\" value=\"");
      out.print(defCentrales.get(i).getCod_jugador());
      out.write('"');
      out.write('>');
      out.print(defCentrales.get(i).getNombre() );
      out.write("</option>\r\n");
      out.write("											");
}; 
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("											\r\n");
      out.write("											<!-- Delantero 2 -->\r\n");
      out.write("											<label>Delantero 2:</label>\r\n");
      out.write("											<select id=\"codDelantero2\" name=\"codDelantero2\">\r\n");
      out.write("											");

											for(int i = 0; i < delanteros.size(); i++) { 
      out.write("\r\n");
      out.write("												<option data-img_src=\"images/jugadores/");
      out.print(delanteros.get(i).getCod_jugador() );
      out.write(".png\" value=\"");
      out.print(delanteros.get(i).getCod_jugador());
      out.write('"');
      out.write('>');
      out.print(delanteros.get(i).getNombre() );
      out.write("</option>\r\n");
      out.write("											");
}; 
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("											\r\n");
      out.write("										</div>\r\n");
      out.write("										\r\n");
      out.write("										<div class=\"\">\r\n");
      out.write("											<!-- Defensa central 2 -->\r\n");
      out.write("											<label>Defensa central 2:</label>\r\n");
      out.write("											<select id=\"codDefCentral2\" name=\"codDefCentral2\">\r\n");
      out.write("											");

											for(int i = 0; i < defCentrales.size(); i++) { 
      out.write("\r\n");
      out.write("												<option data-img_src=\"images/jugadores/");
      out.print(defCentrales.get(i).getCod_jugador() );
      out.write(".png\" value=\"");
      out.print(defCentrales.get(i).getCod_jugador());
      out.write('"');
      out.write('>');
      out.print(defCentrales.get(i).getNombre() );
      out.write("</option>\r\n");
      out.write("											");
}; 
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("											\r\n");
      out.write("											<!-- Centrocampista 1 -->\r\n");
      out.write("											<label>Centrocampista 1:</label>\r\n");
      out.write("											<select id=\"codCentrocampista1\" name=\"codCentrocampista1\">\r\n");
      out.write("											");

											for(int i = 0; i < centrocampistas.size(); i++) { 
      out.write("\r\n");
      out.write("												<option data-img_src=\"images/jugadores/");
      out.print(centrocampistas.get(i).getCod_jugador() );
      out.write(".png\" value=\"");
      out.print(centrocampistas.get(i).getCod_jugador());
      out.write('"');
      out.write('>');
      out.print(centrocampistas.get(i).getNombre() );
      out.write("</option>\r\n");
      out.write("											");
}; 
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("											\r\n");
      out.write("										</div>\r\n");
      out.write("										\r\n");
      out.write("										<div class=\"\">\r\n");
      out.write("											<!-- Lateral derecho -->\r\n");
      out.write("											<label>Lateral derecho:</label>\r\n");
      out.write("											<select id=\"codLatDer\" name=\"codLatDer\">\r\n");
      out.write("											");

											for(int i = 0; i < latDrc.size(); i++) { 
      out.write("\r\n");
      out.write("												<option data-img_src=\"images/jugadores/");
      out.print(latDrc.get(i).getCod_jugador() );
      out.write(".png\" value=\"");
      out.print(latDrc.get(i).getCod_jugador());
      out.write('"');
      out.write('>');
      out.print(latDrc.get(i).getNombre() );
      out.write("</option>\r\n");
      out.write("											");
}; 
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("																						\r\n");
      out.write("											<!-- Centrocampista 2 -->\r\n");
      out.write("											<label>Centrocampista 2:</label>\r\n");
      out.write("											<select id=\"codCentrocampista2\" name=\"codCentrocampista2\">\r\n");
      out.write("											");

											for(int i = 0; i < centrocampistas.size(); i++) { 
      out.write("\r\n");
      out.write("												<option data-img_src=\"images/jugadores/");
      out.print(centrocampistas.get(i).getCod_jugador() );
      out.write(".png\" value=\"");
      out.print(centrocampistas.get(i).getCod_jugador());
      out.write('"');
      out.write('>');
      out.print(centrocampistas.get(i).getNombre() );
      out.write("</option>\r\n");
      out.write("											");
}; 
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("											\r\n");
      out.write("										</div>\r\n");
      out.write("										\r\n");
      out.write("										<div class=\"\">\r\n");
      out.write("											<!-- Lateral izquierdo -->\r\n");
      out.write("											<label>Lateral izquierdo:</label>\r\n");
      out.write("											<select id=\"codLatIzq\" name=\"codLatIzq\">\r\n");
      out.write("											");

											for(int i = 0; i < latIzq.size(); i++) { 
      out.write("\r\n");
      out.write("												<option data-img_src=\"images/jugadores/");
      out.print(latIzq.get(i).getCod_jugador() );
      out.write(".png\" value=\"");
      out.print(latIzq.get(i).getCod_jugador());
      out.write('"');
      out.write('>');
      out.print(latIzq.get(i).getNombre() );
      out.write("</option>\r\n");
      out.write("											");
}; 
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("											\r\n");
      out.write("											<!-- Extremo izquierdo -->\r\n");
      out.write("											<label>Extremo izquierdo:</label>\r\n");
      out.write("											<select id=\"codExtIzq\" name=\"codExtIzq\">\r\n");
      out.write("											");

											for(int i = 0; i < extremosIzq.size(); i++) { 
      out.write("\r\n");
      out.write("												<option data-img_src=\"images/jugadores/");
      out.print(extremosIzq.get(i).getCod_jugador() );
      out.write(".png\" value=\"");
      out.print(extremosIzq.get(i).getCod_jugador());
      out.write('"');
      out.write('>');
      out.print(extremosIzq.get(i).getNombre() );
      out.write("</option>\r\n");
      out.write("											");
}; 
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("											\r\n");
      out.write("										</div>\r\n");
      out.write("										\r\n");
      out.write("										<div class=\"\">\r\n");
      out.write("											<!-- Extremo derecho -->\r\n");
      out.write("											<label>Extremo derecho:</label>\r\n");
      out.write("											<select id=\"codExtDer\" name=\"codExtDer\">\r\n");
      out.write("											");

											for(int i = 0; i < extremosDrc.size(); i++) { 
      out.write("\r\n");
      out.write("												<option data-img_src=\"images/jugadores/");
      out.print(extremosDrc.get(i).getCod_jugador() );
      out.write(".png\" value=\"");
      out.print(extremosDrc.get(i).getCod_jugador());
      out.write('"');
      out.write('>');
      out.print(extremosDrc.get(i).getNombre() );
      out.write("</option>\r\n");
      out.write("											");
}; 
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("											\r\n");
      out.write("										</div>\r\n");
      out.write("										\r\n");
      out.write("										<!-- FIN -->\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("									<div style=\"padding-top:22px;\">\r\n");
      out.write("											<ul class=\"actions\">\r\n");
      out.write("												<li><input type=\"submit\" class=\"button alt\" value=\"Siguiente\" /></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("								</form>\r\n");
      out.write("							</section>\r\n");
      out.write("								</article>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("										\r\n");
      out.write("			<!-- Footer -->\r\n");
      out.write("				<div id=\"footer\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<section class=\"col-3 col-6-narrower col-12-mobilep\">\r\n");
      out.write("								<h3>Listados</h3>\r\n");
      out.write("								<ul class=\"links\">\r\n");
      out.write("									<li><a href=\"jugadores.asp\">Listado de Jugadores</a></li>\r\n");
      out.write("									<li><a href=\"equipos.asp\">Listado de Equipos</a></li>\r\n");
      out.write("									<li><a href=\"ligas.asp\">Listado de Ligas</a></li>\r\n");
      out.write("								\r\n");
      out.write("								</ul>\r\n");
      out.write("							</section>\r\n");
      out.write("							<section class=\"col-3 col-6-narrower col-12-mobilep\">\r\n");
      out.write("								<h3>Más Opciones</h3>\r\n");
      out.write("								<ul class=\"links\">\r\n");
      out.write("									<li><a href=\"altaJugador.jsp\">Alta Jugador</a></li>\r\n");
      out.write("									<li><a href=\"altaEquipo.jsp\">Alta Equipo</a></li>\r\n");
      out.write("									<li><a href=\"altaLiga.jsp\">Alta Liga</a></li>\r\n");
      out.write("									<li><a href=\"altaCarta.jsp\">Alta Carta</a></li>\r\n");
      out.write("									<li><a href=\"modifiJugador.jsp\">Modificar Jugador</a></li>\r\n");
      out.write("									<li><a href=\"modifiEquipo.jsp\">Modificar Equipo</a></li>\r\n");
      out.write("									<li><a href=\"modifiLiga.jsp\">Modificar Liga</a></li>\r\n");
      out.write("									<li><a href=\"modifiCarta.jsp\">Modificar Carta</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</section>\r\n");
      out.write("							<section class=\"col-6 col-12-narrower\">\r\n");
      out.write("								<h3>Solicita Información</h3>\r\n");
      out.write("								<form>\r\n");
      out.write("									<div class=\"row gtr-50\">\r\n");
      out.write("										<div class=\"col-6 col-12-mobilep\">\r\n");
      out.write("											<input type=\"text\" name=\"name\" id=\"name\" placeholder=\"Name\" />\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-6 col-12-mobilep\">\r\n");
      out.write("											<input type=\"email\" name=\"email\" id=\"email\" placeholder=\"Email\" />\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-12\">\r\n");
      out.write("											<textarea name=\"message\" id=\"message\" placeholder=\"Message\" rows=\"5\"></textarea>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-12\">\r\n");
      out.write("											<ul class=\"actions\">\r\n");
      out.write("												<li><input type=\"submit\" class=\"button alt\" value=\"Enviar Email\" /></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form>\r\n");
      out.write("							</section>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- Icons -->\r\n");
      out.write("						<ul class=\"icons\">\r\n");
      out.write("							<li><a href=\"#\" class=\"icon fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"icon fa-facebook\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"icon fa-github\"><span class=\"label\">GitHub</span></a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"icon fa-linkedin\"><span class=\"label\">LinkedIn</span></a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"icon fa-google-plus\"><span class=\"label\">Google+</span></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("\r\n");
      out.write("					<!-- Copyright -->\r\n");
      out.write("						<div class=\"copyright\">\r\n");
      out.write("							<ul class=\"menu\">\r\n");
      out.write("								<li>&copy; FIFA 23. Todos los derechos reservados</li><li>Design: <a href=\"https://www.centronelson.org\">Centro Nelson</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Scripts -->\r\n");
      out.write("			<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/index.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/dropdown.js\"></script>\r\n");
      out.write("			\r\n");
      out.write("	<!-- 4 -->\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Inicio -->\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function custom_template(obj){\r\n");
      out.write("            var data = $(obj.element).data();\r\n");
      out.write("            var text = $(obj.element).text();\r\n");
      out.write("            if(data && data['img_src']){\r\n");
      out.write("                img_src = data['img_src'];\r\n");
      out.write("                template = $(\"<div style=\\\"display:flex; align-items: center;\\\"><img src=\\\"\" + img_src + \"\\\" style=\\\"width:80px; height:60px; padding-right:1rem\\\"/><p style=\\\"font-weight:700; font-size:14pt; \\\">\" + text + \"</p></div>\");\r\n");
      out.write("                return template;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    	var options = {\r\n");
      out.write("        'templateSelection': custom_template,\r\n");
      out.write("        'templateResult': custom_template,\r\n");
      out.write("    	}\r\n");
      out.write("    	$('#codPortero').select2(options);\r\n");
      out.write("    	$('.select2-container--default .select2-selection--single').css({'height': '65px'});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function custom_template(obj){\r\n");
      out.write("            var data = $(obj.element).data();\r\n");
      out.write("            var text = $(obj.element).text();\r\n");
      out.write("            if(data && data['img_src']){\r\n");
      out.write("                img_src = data['img_src'];\r\n");
      out.write("                template = $(\"<div style=\\\"display:flex; align-items: center;\\\"><img src=\\\"\" + img_src + \"\\\" style=\\\"width:80px; height:60px; padding-right:1rem\\\"/><p style=\\\"font-weight:700; font-size:14pt; \\\">\" + text + \"</p></div>\");\r\n");
      out.write("                return template;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    	var options = {\r\n");
      out.write("        'templateSelection': custom_template,\r\n");
      out.write("        'templateResult': custom_template,\r\n");
      out.write("    	}\r\n");
      out.write("    	$('#codDefCentral1').select2(options);\r\n");
      out.write("    	$('.select2-container--default .select2-selection--single').css({'height': '65px'});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function custom_template(obj){\r\n");
      out.write("            var data = $(obj.element).data();\r\n");
      out.write("            var text = $(obj.element).text();\r\n");
      out.write("            if(data && data['img_src']){\r\n");
      out.write("                img_src = data['img_src'];\r\n");
      out.write("                template = $(\"<div style=\\\"display:flex; align-items: center;\\\"><img src=\\\"\" + img_src + \"\\\" style=\\\"width:80px; height:60px; padding-right:1rem\\\"/><p style=\\\"font-weight:700; font-size:14pt; \\\">\" + text + \"</p></div>\");\r\n");
      out.write("                return template;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    	var options = {\r\n");
      out.write("        'templateSelection': custom_template,\r\n");
      out.write("        'templateResult': custom_template,\r\n");
      out.write("    	}\r\n");
      out.write("    	$('#codDefCentral2').select2(options);\r\n");
      out.write("    	$('.select2-container--default .select2-selection--single').css({'height': '65px'});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function custom_template(obj){\r\n");
      out.write("            var data = $(obj.element).data();\r\n");
      out.write("            var text = $(obj.element).text();\r\n");
      out.write("            if(data && data['img_src']){\r\n");
      out.write("                img_src = data['img_src'];\r\n");
      out.write("                template = $(\"<div style=\\\"display:flex; align-items: center;\\\"><img src=\\\"\" + img_src + \"\\\" style=\\\"width:80px; height:60px; padding-right:1rem\\\"/><p style=\\\"font-weight:700; font-size:14pt; \\\">\" + text + \"</p></div>\");\r\n");
      out.write("                return template;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    	var options = {\r\n");
      out.write("        'templateSelection': custom_template,\r\n");
      out.write("        'templateResult': custom_template,\r\n");
      out.write("    	}\r\n");
      out.write("    	$('#codLatDer').select2(options);\r\n");
      out.write("    	$('.select2-container--default .select2-selection--single').css({'height': '65px'});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function custom_template(obj){\r\n");
      out.write("            var data = $(obj.element).data();\r\n");
      out.write("            var text = $(obj.element).text();\r\n");
      out.write("            if(data && data['img_src']){\r\n");
      out.write("                img_src = data['img_src'];\r\n");
      out.write("                template = $(\"<div style=\\\"display:flex; align-items: center;\\\"><img src=\\\"\" + img_src + \"\\\" style=\\\"width:80px; height:60px; padding-right:1rem\\\"/><p style=\\\"font-weight:700; font-size:14pt; \\\">\" + text + \"</p></div>\");\r\n");
      out.write("                return template;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    	var options = {\r\n");
      out.write("        'templateSelection': custom_template,\r\n");
      out.write("        'templateResult': custom_template,\r\n");
      out.write("    	}\r\n");
      out.write("    	$('#codLatIzq').select2(options);\r\n");
      out.write("    	$('.select2-container--default .select2-selection--single').css({'height': '65px'});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function custom_template(obj){\r\n");
      out.write("            var data = $(obj.element).data();\r\n");
      out.write("            var text = $(obj.element).text();\r\n");
      out.write("            if(data && data['img_src']){\r\n");
      out.write("                img_src = data['img_src'];\r\n");
      out.write("                template = $(\"<div style=\\\"display:flex; align-items: center;\\\"><img src=\\\"\" + img_src + \"\\\" style=\\\"width:80px; height:60px; padding-right:1rem\\\"/><p style=\\\"font-weight:700; font-size:14pt; \\\">\" + text + \"</p></div>\");\r\n");
      out.write("                return template;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    	var options = {\r\n");
      out.write("        'templateSelection': custom_template,\r\n");
      out.write("        'templateResult': custom_template,\r\n");
      out.write("    	}\r\n");
      out.write("    	$('#codDelantero1').select2(options);\r\n");
      out.write("    	$('.select2-container--default .select2-selection--single').css({'height': '65px'});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function custom_template(obj){\r\n");
      out.write("            var data = $(obj.element).data();\r\n");
      out.write("            var text = $(obj.element).text();\r\n");
      out.write("            if(data && data['img_src']){\r\n");
      out.write("                img_src = data['img_src'];\r\n");
      out.write("                template = $(\"<div style=\\\"display:flex; align-items: center;\\\"><img src=\\\"\" + img_src + \"\\\" style=\\\"width:80px; height:60px; padding-right:1rem\\\"/><p style=\\\"font-weight:700; font-size:14pt; \\\">\" + text + \"</p></div>\");\r\n");
      out.write("                return template;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    	var options = {\r\n");
      out.write("        'templateSelection': custom_template,\r\n");
      out.write("        'templateResult': custom_template,\r\n");
      out.write("    	}\r\n");
      out.write("    	$('#codDelantero2').select2(options);\r\n");
      out.write("    	$('.select2-container--default .select2-selection--single').css({'height': '65px'});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function custom_template(obj){\r\n");
      out.write("            var data = $(obj.element).data();\r\n");
      out.write("            var text = $(obj.element).text();\r\n");
      out.write("            if(data && data['img_src']){\r\n");
      out.write("                img_src = data['img_src'];\r\n");
      out.write("                template = $(\"<div style=\\\"display:flex; align-items: center;\\\"><img src=\\\"\" + img_src + \"\\\" style=\\\"width:80px; height:60px; padding-right:1rem\\\"/><p style=\\\"font-weight:700; font-size:14pt; \\\">\" + text + \"</p></div>\");\r\n");
      out.write("                return template;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    	var options = {\r\n");
      out.write("        'templateSelection': custom_template,\r\n");
      out.write("        'templateResult': custom_template,\r\n");
      out.write("    	}\r\n");
      out.write("    	$('#codCentrocampista1').select2(options);\r\n");
      out.write("    	$('.select2-container--default .select2-selection--single').css({'height': '65px'});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function custom_template(obj){\r\n");
      out.write("            var data = $(obj.element).data();\r\n");
      out.write("            var text = $(obj.element).text();\r\n");
      out.write("            if(data && data['img_src']){\r\n");
      out.write("                img_src = data['img_src'];\r\n");
      out.write("                template = $(\"<div style=\\\"display:flex; align-items: center;\\\"><img src=\\\"\" + img_src + \"\\\" style=\\\"width:80px; height:60px; padding-right:1rem\\\"/><p style=\\\"font-weight:700; font-size:14pt; \\\">\" + text + \"</p></div>\");\r\n");
      out.write("                return template;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    	var options = {\r\n");
      out.write("        'templateSelection': custom_template,\r\n");
      out.write("        'templateResult': custom_template,\r\n");
      out.write("    	}\r\n");
      out.write("    	$('#codCentrocampista2').select2(options);\r\n");
      out.write("    	$('.select2-container--default .select2-selection--single').css({'height': '65px'});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function custom_template(obj){\r\n");
      out.write("            var data = $(obj.element).data();\r\n");
      out.write("            var text = $(obj.element).text();\r\n");
      out.write("            if(data && data['img_src']){\r\n");
      out.write("                img_src = data['img_src'];\r\n");
      out.write("                template = $(\"<div style=\\\"display:flex; align-items: center;\\\"><img src=\\\"\" + img_src + \"\\\" style=\\\"width:80px; height:60px; padding-right:1rem\\\"/><p style=\\\"font-weight:700; font-size:14pt; \\\">\" + text + \"</p></div>\");\r\n");
      out.write("                return template;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    	var options = {\r\n");
      out.write("        'templateSelection': custom_template,\r\n");
      out.write("        'templateResult': custom_template,\r\n");
      out.write("    	}\r\n");
      out.write("    	$('#codExtIzq').select2(options);\r\n");
      out.write("    	$('.select2-container--default .select2-selection--single').css({'height': '65px'});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function custom_template(obj){\r\n");
      out.write("            var data = $(obj.element).data();\r\n");
      out.write("            var text = $(obj.element).text();\r\n");
      out.write("            if(data && data['img_src']){\r\n");
      out.write("                img_src = data['img_src'];\r\n");
      out.write("                template = $(\"<div style=\\\"display:flex; align-items: center;\\\"><img src=\\\"\" + img_src + \"\\\" style=\\\"width:80px; height:60px; padding-right:1rem\\\"/><p style=\\\"font-weight:700; font-size:14pt; \\\">\" + text + \"</p></div>\");\r\n");
      out.write("                return template;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    	var options = {\r\n");
      out.write("        'templateSelection': custom_template,\r\n");
      out.write("        'templateResult': custom_template,\r\n");
      out.write("    	}\r\n");
      out.write("    	$('#codExtDer').select2(options);\r\n");
      out.write("    	$('.select2-container--default .select2-selection--single').css({'height': '65px'});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Fin -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
