/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2023-03-17 14:57:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Coches.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("Coches");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");

    

    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Tabla de datos</title>\r\n");
      out.write("<meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Header -->\r\n");

ArrayList<Coche> datosCoches = Main.devolverArrayCoches();
out.print(datosCoches.size()); 

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("  <div class=\"shell\">\r\n");
      out.write("    <!-- Logo + Top Nav -->\r\n");
      out.write("    <div id=\"top\">\r\n");
      out.write("      <h1><a href=\"#\">Tabla de datos</a></h1>\r\n");
      out.write("      <div id=\"top-navigation\"><a href=\"#\"><strong></strong></a> <span>|</span> <a href=\"#\"></a> <span>|</span> <a href=\"#\"></a> <span>|</span> <a href=\"#\"></a> </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End Header -->\r\n");
      out.write("<!-- Container -->\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("  <div class=\"shell\">\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    <br />\r\n");
      out.write("    <!-- Main -->\r\n");
      out.write("    <div id=\"main\">\r\n");
      out.write("      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("      <!-- Content -->\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("        <!-- Box -->\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("          <!-- Box Head -->\r\n");
      out.write("          <div class=\"box-head\">\r\n");
      out.write("            <h2 class=\"left\">Listado de coches</h2>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- End Box Head -->\r\n");
      out.write("          <!-- Table -->\r\n");
      out.write("          <div class=\"table\">\r\n");
      out.write("            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <th>Matrícula</th>\r\n");
      out.write("                <th>Marca</th>\r\n");
      out.write("                <th>Modelo</th>\r\n");
      out.write("                <th>Color</th>\r\n");
      out.write("                <th>Precio</th>\r\n");
      out.write("                <th>Complementos</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <!-- tr y td -->\r\n");
      out.write("              ");

              
              for(int i = 0; i < datosCoches.size(); i++) {
            	  out.print("<tr>");
            	  
            	  out.print("<td>" + datosCoches.get(i).getMatricula() + "</td>");
            	  out.print("<td>" + datosCoches.get(i).getMarca() + "</td>");
            	  out.print("<td>" + datosCoches.get(i).getModelo() + "</td>");
            	  out.print("<td>" + datosCoches.get(i).getColor() + "</td>");
            	  out.print("<td>" + datosCoches.get(i).getPrecio() + "</td>");
            	  out.print("<td>" + datosCoches.get(i).getComplementos() + "</td>");
            	  
            	  out.print("<td>");
              }
              
              
      out.write("\r\n");
      out.write("              <!--  -->\r\n");
      out.write("            </table>\r\n");
      out.write("            <!-- Pagging -->\r\n");
      out.write("            <div class=\"pagging\">\r\n");
      out.write("              <div class=\"left\"></div>\r\n");
      out.write("              <div class=\"right\">  </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Pagging -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Table -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Box -->\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- End Content -->\r\n");
      out.write("      <!-- Sidebar -->\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Main -->\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End Container -->\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("  <div class=\"shell\"> <span class=\"left\">&copy; 2010 - Centro Nelson</span> <span class=\"right\"> Design by <a href=\"http://chocotemplates.com\">Alejandro Enriquez</a> </span> </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End Footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
